# Generated by Django 2.0.5 on 2018-08-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unswcode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
