# Generated by Django 2.0.5 on 2018-08-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unswcode', '0004_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.CharField(default='CODE12340TEST', max_length=9999),
            preserve_default=False,
        ),
    ]
