# Generated by Django 2.0.5 on 2018-09-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unswcode', '0005_submission_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='mark',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='link',
            field=models.TextField(max_length=1000),
        ),
    ]
