# Generated by Django 2.0.5 on 2018-07-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rb_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archiJson', models.TextField(max_length=99999)),
                ('displayGeom', models.TextField(blank=True, max_length=99999, null=True)),
            ],
        ),
    ]
