# Generated by Django 2.0.5 on 2018-06-07 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180607_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finish',
            old_name='type',
            new_name='ftype',
        ),
    ]
