# Generated by Django 2.0.5 on 2018-06-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180607_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finish',
            name='ftype',
        ),
    ]
