# Generated by Django 2.0.5 on 2018-06-14 16:09

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_finish_ftype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finishcode',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='room',
            name='myfield',
            field=markdownx.models.MarkdownxField(default='Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='representative',
            field=models.CharField(default='Text', max_length=200),
            preserve_default=False,
        ),
    ]
