# Generated by Django 2.0.5 on 2018-07-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('basecost', models.IntegerField()),
                ('type', models.CharField(blank=True, choices=[('P', 'Physical'), ('M', 'Mental'), ('B', 'Physical/Mental')], max_length=1, null=True)),
                ('sources', models.CharField(blank=True, choices=[('E', 'Exotic')], max_length=1, null=True)),
                ('description', models.TextField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('occupation', models.CharField(max_length=120)),
                ('attributesText', models.CharField(max_length=2000)),
                ('drText', models.CharField(max_length=2000)),
                ('reactions', models.CharField(max_length=2000)),
                ('notes', models.CharField(blank=True, max_length=9000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='characterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='modifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('modifier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='modPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='rel_advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('advantage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrpgtest.advantage')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrpgtest.character')),
                ('modifiers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrpgtest.modPackage')),
            ],
        ),
        migrations.CreateModel(
            name='specialmodifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=9999)),
                ('modifier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='modifier',
            name='modPackage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrpgtest.modPackage'),
        ),
        migrations.AddField(
            model_name='character',
            name='advantages',
            field=models.ManyToManyField(blank=True, through='scrpgtest.rel_advantage', to='scrpgtest.advantage'),
        ),
        migrations.AddField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrpgtest.campaign'),
        ),
        migrations.AddField(
            model_name='character',
            name='characterType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrpgtest.characterType'),
        ),
        migrations.AddField(
            model_name='character',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrpgtest.character'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrpgtest.race'),
        ),
        migrations.AddField(
            model_name='character',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrpgtest.status'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='speciallimitations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrpgtest.specialmodifier'),
        ),
    ]
