# Generated by Django 2.0.5 on 2018-07-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrpgtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='disadvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('basecost', models.IntegerField()),
                ('type', models.CharField(blank=True, choices=[('P', 'Physical'), ('M', 'Mental'), ('B', 'Physical/Mental')], max_length=1, null=True)),
                ('sources', models.CharField(blank=True, choices=[('E', 'Exotic')], max_length=1, null=True)),
                ('description', models.TextField(max_length=9999)),
                ('speciallimitations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrpgtest.specialmodifier')),
            ],
        ),
        migrations.CreateModel(
            name='rel_disadvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrpgtest.character')),
                ('disadvantage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrpgtest.disadvantage')),
            ],
        ),
        migrations.RemoveField(
            model_name='modpackage',
            name='packageName',
        ),
        migrations.AddField(
            model_name='rel_disadvantage',
            name='modifiers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrpgtest.modPackage'),
        ),
        migrations.AddField(
            model_name='character',
            name='disadvantages',
            field=models.ManyToManyField(blank=True, through='scrpgtest.rel_disadvantage', to='scrpgtest.disadvantage'),
        ),
    ]
