# Generated by Django 2.1.1 on 2018-09-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrpgtest', '0002_auto_20180703_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='rel_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relskill', to='scrpgtest.character')),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=120)),
                ('skill_challenge', models.CharField(blank=True, choices=[('E', 'Easy'), ('A', 'Average'), ('H', 'Hard'), ('VH', 'Very Hard')], max_length=2, null=True)),
                ('skill_attribute', models.CharField(blank=True, choices=[('DX', 'Dexterity'), ('IQ', 'Intelligence'), ('HT', 'Health'), ('Per', 'Perception'), ('Will', 'Will')], max_length=4, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rel_advantage',
            name='advantage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reladvantage', to='scrpgtest.advantage'),
        ),
        migrations.AlterField(
            model_name='rel_advantage',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reladvantage', to='scrpgtest.character'),
        ),
        migrations.AlterField(
            model_name='rel_disadvantage',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reldisadvantage', to='scrpgtest.character'),
        ),
        migrations.AlterField(
            model_name='rel_disadvantage',
            name='disadvantage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reldisadvantage', to='scrpgtest.disadvantage'),
        ),
        migrations.AddField(
            model_name='rel_skill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relskill', to='scrpgtest.skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(blank=True, through='scrpgtest.rel_skill', to='scrpgtest.skill'),
        ),
    ]
