# Generated by Django 2.1.1 on 2018-09-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrpgtest', '0003_auto_20180909_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='rel_language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written', models.IntegerField(blank=True, null=True)),
                ('spoken', models.IntegerField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rellanguage', to='scrpgtest.character')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rellanguage', to='scrpgtest.language')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_description',
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='languages',
            field=models.ManyToManyField(blank=True, through='scrpgtest.rel_language', to='scrpgtest.language'),
        ),
    ]
