# Generated by Django 2.1.1 on 2018-09-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrpgtest', '0004_auto_20180909_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dx',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='ht',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='iq',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='st',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='rel_language',
            name='spoken',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Broken'), (2, 'Accented'), (3, 'Fluent')], null=True),
        ),
        migrations.AlterField(
            model_name='rel_language',
            name='written',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Broken'), (2, 'Accented'), (3, 'Fluent')], null=True),
        ),
    ]
