# Generated by Django 2.1.1 on 2018-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrpgtest', '0005_auto_20180909_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bm',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='character',
            name='bs',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='character',
            name='fp',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='per',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='will',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_attribute',
            field=models.CharField(blank=True, choices=[('dx', 'Dexterity'), ('iq', 'Intelligence'), ('ht', 'Health'), ('per', 'Perception'), ('will', 'Will')], max_length=4, null=True),
        ),
    ]
