# Generated by Django 2.1.1 on 2018-09-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrpgtest', '0006_auto_20180909_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='effect',
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
    ]
