# Generated by Django 2.1.1 on 2018-10-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrpgtest', '0007_advantage_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sm',
            field=models.IntegerField(default=1),
        ),
    ]
