# Generated by Django 2.1.1 on 2018-10-14 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrpgtest', '0008_character_sm'),
    ]

    operations = [
        migrations.CreateModel(
            name='possession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession_name', models.CharField(max_length=120)),
                ('possession_description', models.TextField(blank=True, max_length=9999, null=True)),
                ('possession_weight', models.IntegerField(default=0)),
                ('possession_cost', models.IntegerField(default=0)),
                ('meleeStats', models.TextField(blank=True, max_length=9999, null=True)),
                ('rangeStats', models.TextField(blank=True, max_length=9999, null=True)),
                ('armourStats', models.TextField(blank=True, max_length=9999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rel_possession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relpossession', to='scrpgtest.character')),
                ('possession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relpossession', to='scrpgtest.possession')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='possessions',
            field=models.ManyToManyField(blank=True, through='scrpgtest.rel_possession', to='scrpgtest.possession'),
        ),
    ]
