# Generated by Django 2.1.1 on 2018-10-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrpgtest', '0010_auto_20181014_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_defaults',
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
    ]
