# Generated by Django 2.1.3 on 2019-01-07 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='panorama',
            old_name='name',
            new_name='panorama_name',
        ),
        migrations.AddField(
            model_name='panorama',
            name='collection',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='panorama.collection'),
            preserve_default=False,
        ),
    ]
