# Generated by Django 2.1.3 on 2019-01-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0002_auto_20190107_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panorama',
            old_name='left_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='panorama',
            name='right_image',
        ),
        migrations.AddField(
            model_name='panorama',
            name='stereoscopic',
            field=models.BooleanField(default=True),
        ),
    ]
