# Generated by Django 2.1.3 on 2019-01-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0003_auto_20190107_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panorama',
            name='stereoscopic',
            field=models.BooleanField(default=False),
        ),
    ]
