# Generated by Django 2.1.3 on 2019-01-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0005_panorama_extraimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='panorama_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
