# Generated by Django 2.1.3 on 2019-01-07 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0006_auto_20190107_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panorama',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panorama', to='panorama.collection'),
        ),
    ]
